// <auto-generated />
namespace CareerCloud.EntityFrameworkDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_countrycodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_countrycodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201903310516250_added_countrycodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
